// Base nutricional simplificada — referência por 100g/100ml salvo indicado
// kcal, c (carbo g), p (proteína g), g (gordura g)
window.FOODS = [
  { nome: "Arroz branco cozido", unidade: "g", kcal: 130, c: 28.2, p: 2.7, g: 0.3, cat: "Cereais" },
  { nome: "Arroz integral cozido", unidade: "g", kcal: 124, c: 25.8, p: 2.6, g: 1.0, cat: "Cereais" },
  { nome: "Macarrão cozido", unidade: "g", kcal: 158, c: 31.0, p: 5.8, g: 0.9, cat: "Cereais" },
  { nome: "Quinoa cozida", unidade: "g", kcal: 120, c: 21.3, p: 4.4, g: 1.9, cat: "Cereais" },
  { nome: "Aveia em flocos", unidade: "g", kcal: 389, c: 66.3, p: 16.9, g: 6.9, cat: "Cereais" },
  { nome: "Pão francês", unidade: "g", kcal: 300, c: 58.6, p: 8.0, g: 3.1, cat: "Pães" },
  { nome: "Pão integral", unidade: "g", kcal: 247, c: 41.2, p: 10.0, g: 4.0, cat: "Pães" },
  { nome: "Tapioca", unidade: "g", kcal: 240, c: 60.0, p: 0.0, g: 0.0, cat: "Pães" },
  { nome: "Batata inglesa cozida", unidade: "g", kcal: 87, c: 20.1, p: 1.9, g: 0.1, cat: "Tubérculos" },
  { nome: "Batata doce cozida", unidade: "g", kcal: 86, c: 20.1, p: 1.6, g: 0.1, cat: "Tubérculos" },
  { nome: "Mandioca cozida", unidade: "g", kcal: 125, c: 30.1, p: 0.6, g: 0.3, cat: "Tubérculos" },
  { nome: "Inhame cozido", unidade: "g", kcal: 97, c: 23.2, p: 2.0, g: 0.2, cat: "Tubérculos" },
  { nome: "Feijão preto cozido", unidade: "g", kcal: 77, c: 14.0, p: 4.5, g: 0.5, cat: "Leguminosas" },
  { nome: "Feijão carioca cozido", unidade: "g", kcal: 76, c: 13.6, p: 4.8, g: 0.5, cat: "Leguminosas" },
  { nome: "Lentilha cozida", unidade: "g", kcal: 116, c: 20.1, p: 9.0, g: 0.4, cat: "Leguminosas" },
  { nome: "Grão de bico cozido", unidade: "g", kcal: 164, c: 27.4, p: 8.9, g: 2.6, cat: "Leguminosas" },
  { nome: "Frango grelhado (peito)", unidade: "g", kcal: 165, c: 0, p: 31.0, g: 3.6, cat: "Carnes" },
  { nome: "Patinho bovino grelhado", unidade: "g", kcal: 219, c: 0, p: 35.9, g: 7.3, cat: "Carnes" },
  { nome: "Salmão grelhado", unidade: "g", kcal: 208, c: 0, p: 20.4, g: 13.4, cat: "Carnes" },
  { nome: "Tilápia grelhada", unidade: "g", kcal: 128, c: 0, p: 26.2, g: 2.7, cat: "Carnes" },
  { nome: "Atum em água", unidade: "g", kcal: 116, c: 0, p: 26.0, g: 1.0, cat: "Carnes" },
  { nome: "Ovo de galinha", unidade: "g", kcal: 155, c: 1.1, p: 13.0, g: 11.0, cat: "Ovos" },
  { nome: "Clara de ovo", unidade: "g", kcal: 52, c: 0.7, p: 10.9, g: 0.2, cat: "Ovos" },
  { nome: "Leite integral", unidade: "ml", kcal: 61, c: 4.8, p: 3.2, g: 3.3, cat: "Laticínios" },
  { nome: "Leite desnatado", unidade: "ml", kcal: 35, c: 4.9, p: 3.4, g: 0.2, cat: "Laticínios" },
  { nome: "Iogurte natural integral", unidade: "g", kcal: 61, c: 4.7, p: 3.5, g: 3.3, cat: "Laticínios" },
  { nome: "Iogurte grego natural", unidade: "g", kcal: 97, c: 3.6, p: 9.0, g: 5.0, cat: "Laticínios" },
  { nome: "Queijo mussarela", unidade: "g", kcal: 280, c: 3.1, p: 22.2, g: 19.5, cat: "Laticínios" },
  { nome: "Queijo cottage", unidade: "g", kcal: 98, c: 3.4, p: 11.1, g: 4.3, cat: "Laticínios" },
  { nome: "Requeijão cremoso", unidade: "g", kcal: 257, c: 3.0, p: 9.6, g: 23.0, cat: "Laticínios" },
  { nome: "Banana prata", unidade: "g", kcal: 89, c: 22.8, p: 1.1, g: 0.3, cat: "Frutas" },
  { nome: "Maçã", unidade: "g", kcal: 52, c: 13.8, p: 0.3, g: 0.2, cat: "Frutas" },
  { nome: "Mamão papaya", unidade: "g", kcal: 43, c: 10.8, p: 0.5, g: 0.3, cat: "Frutas" },
  { nome: "Morango", unidade: "g", kcal: 32, c: 7.7, p: 0.7, g: 0.3, cat: "Frutas" },
  { nome: "Abacate", unidade: "g", kcal: 160, c: 8.5, p: 2.0, g: 14.7, cat: "Frutas" },
  { nome: "Manga", unidade: "g", kcal: 60, c: 15.0, p: 0.8, g: 0.4, cat: "Frutas" },
  { nome: "Azeite de oliva", unidade: "ml", kcal: 884, c: 0, p: 0, g: 100, cat: "Óleos" },
  { nome: "Castanha do Pará", unidade: "g", kcal: 656, c: 12.3, p: 14.3, g: 66.4, cat: "Oleaginosas" },
  { nome: "Amendoim torrado", unidade: "g", kcal: 567, c: 16.1, p: 25.8, g: 49.2, cat: "Oleaginosas" },
  { nome: "Pasta de amendoim", unidade: "g", kcal: 588, c: 20.0, p: 25.0, g: 50.0, cat: "Oleaginosas" },
  { nome: "Chocolate ao leite", unidade: "g", kcal: 535, c: 59.4, p: 7.6, g: 29.7, cat: "Doces" },
  { nome: "Brigadeiro", unidade: "g", kcal: 388, c: 56.0, p: 4.0, g: 16.0, cat: "Doces" },
  { nome: "Açaí com guaraná (polpa)", unidade: "g", kcal: 110, c: 17.0, p: 1.0, g: 4.0, cat: "Frutas" },
];
